name: Newman Postman Collection Runner

on:
  workflow_dispatch:

jobs:
  newman_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install Newman
        run: npm install -g newman

      - name: Install HTMLExtraReporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Newman with Postman Collection
        run: newman run "https://api.postman.com/collections/30087989-2e587edc-b536-41fe-938f-ed9d232813c3?access_key=PMAT-01HQJNSYRXEQH91CHZDHAMYQ56" -r cli,json --reporter-silent
