name: Newman Postman Collection Runner

on:
  workflow_dispatch:

jobs:
  newman_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16' # Specify the Node.js version

      - name: Run Newman with Postman Collection
        run: |
          npm install
          npm start